# Model arguments
model_name_or_path: Qwen/Qwen3-VL-2B-Instruct
model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_name: "/mnt/task_runtime/data/omni_med_vqa_processed_sampled/open_access_sft_data_hf_modality_MRI_train_600"
# dataset_configs:
# - all
# preprocessing_num_workers: 2

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: "no"
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen3-VL-2B-Instruct-SFT
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
packing: true
max_length: 4096
# choose no packing to support custom data collator
packing: false
max_steps: -1
num_train_epochs: 1
output_dir: /mnt/task_runtime/output/SFT/Qwen3-VL-2B-Instruct-SFT-MRI-600
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
report_to: []  # 禁用 wandb
save_strategy: "steps"
save_steps: 100
seed: 42
warmup_ratio: 0.1


